apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Sykepengedager informasjon topic"
    dcat.data.nav.no/description: >-
      Topic inneholder  informasjon om sykepengedager til den sykmeldte.
  name: sykepengedager-informasjon-topic
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: team-esyfo
      application: meroppfolging-backend
      access: read
