style:
  MagicNumber:
    active: false
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
naming:
  ConstructorParameterNaming:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
complexity:
  LongMethod:
    active: false
  NestedBlockDepth:
    active: false
config:
  validation: true
  warningsAsErrors: true
