apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengedager-informasjon
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/health/readinessState
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: sykepengedager-informasjon-db
            envVarPrefix: DB
        diskAutoresize: true
        tier: db-f1-micro
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 600Mi
  vault:
    enabled: false
  kafka:
    pool: nav-dev
  ingresses:
    - "https://sykepengedager-informasjon.intern.dev.nav.no"
  leaderElection: true
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  env:
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://dev-gcp.teamsykefravr.istilgangskontroll/.default
    - name: ISTILGANGSKONTROLL_ID
      value: dev-gcp.teamsykefravr.istilgangskontroll
    - name: DITT_SYKEFRAVAER_CLIENT_ID
      value: "dev-gcp:flex:ditt-sykefravaer"
  accessPolicy:
    inbound:
      rules:
        - application: meroppfolging-backend
        - application: meroppfolging-frontend
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: ditt-sykefravaer
          namespace: flex
    outbound:
      rules:
        - application: istilgangskontroll
          namespace: teamsykefravr

