ALTER TABLE UTBETALING_SPLEIS ADD COLUMN UTBET_TOM DATE;

UPDATE UTBETALING_SPLEIS SET UTBET_TOM = TOM;

DROP VIEW UTBETALINGER;

CREATE VIEW UTBETALINGER
AS
SELECT UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
FROM UTBETALING_INFOTRYGD
UNION ALL
SELECT UUID, FNR, FORELOPIG_BEREGNET_SLUTT, UTBET_TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
FROM UTBETALING_SPLEIS;
