CREATE INDEX CONCURRENTLY spleis_utbetalt_tom_index
    ON UTBETALING_SPLEIS (UTBETALT_TOM, FNR)
    WHERE UTBETALT_TOM IS NOT NULL;

CREATE INDEX CONCURRENTLY spleis_opprettet_index
    ON UTBETALING_SPLEIS (OPPRETTET, FNR)
    WHERE OPPRETTET < '2025-09-11T00:00';
