create view UTBETALING
AS
select UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, UTBET_TOM TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_INFOTRYGD
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, UTBETALT_TOM, TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_SPLEIS WHERE UTBETALT_TOM IS NOT NULL;

create view MAXDATO
AS
select UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, UTBET_TOM TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_INFOTRYGD
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, UTBETALT_TOM, TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_SPLEIS;
