create or replace view UTBETALINGER
AS
select UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_INFOTRYGD
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, UTBETALT_TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
 from UTBETALING_SPLEIS
 where UTBETALT_TOM is not null
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_SPLEIS
where OPPRETTET < '2025-09-11T00:00';

CREATE INDEX CONCURRENTLY IF NOT EXISTS spleis_utbetalt_tom_index
    ON UTBETALING_SPLEIS (UTBETALT_TOM, FNR)
    WHERE UTBETALT_TOM IS NOT NULL;

CREATE INDEX CONCURRENTLY IF NOT EXISTS spleis_opprettet_index
    ON UTBETALING_SPLEIS (OPPRETTET, FNR)
    WHERE OPPRETTET < '2025-09-11T00:00';
