drop view UTBETALINGER;
create view UTBETALINGER
AS
select UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_INFOTRYGD
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, COALESCE(UTBETALT_TOM, TOM), GJENSTAENDE_SYKEDAGER, OPPRETTET
 from UTBETALING_SPLEIS
 where UTBETALT_TOM is not null
    or OPPRETTET < '2025-09-11T00:00';

create index UTBETALING_SPLEIS_OPPRETTET_INDEX on UTBETALING_SPLEIS (OPPRETTET);
