create view MAXDATO
AS
select UUID, FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_INFOTRYGD
union all
select UUID, FNR, FORELOPIG_BEREGNET_SLUTT, TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER, OPPRETTET
from UTBETALING_SPLEIS
