name: Deploy AivenApplication

on:
  push:
    paths:
      - '.nais/aiven-*.yml'
      - '.github/workflows/deploy-aiven.yml'
      - '.nais/nais-prod.yml'
      - '.nais/nais-dev.yml'

jobs:
  deploy:
    strategy:
      matrix:
        name:
          - aiven-sykepengedager-infotrygd.yml
        cluster:
          - dev-gcp
          - prod-gcp
        include:
          - cluster: dev-gcp
            vars: nais-dev.yml
          - cluster: prod-gcp
            vars: nais-prod.yml
    name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/${{ matrix.name }}
          VARS: .nais/${{ matrix.vars }}
          PRINT_PAYLOAD: true
