name: Deploy Aiven Application

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        name:
          - aiven-sykepengedager-infotrygd.yml
        cluster:
          - dev-gcp
          - prod-gcp
        include:
          - cluster: dev-gcp
            vars: nais-dev.yaml
          - cluster: prod-gcp
            vars: nais-prod.yaml

    name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Docker Image
        id: docker-build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true

      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v2
        env:
          TEAM: 'team-esyfo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/${{ matrix.name }}
          VARS: nais/${{ matrix.vars }}
          PRINT_PAYLOAD: true
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
          DEPLOY_SERVER: deploy.nav.cloud.nais.io:443