name: Deploy Aiven Application

on:
  push:
    paths:
      - 'nais/aiven-sykepengedager-infotrygd.yml'
      - '.github/workflows/deploy-aiven.yml'
      - 'nais/nais-prod.yaml'
      - 'nais/nais-dev.yaml'

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@main
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: sykepengedager-informasjon