name: Deploy Aiven Application

on:
  push:
    paths:
      - 'nais/aiven-sykepengedager-infotrygd.yml'
      - '.github/workflows/deploy-aiven.yml'
      - 'nais/nais-prod.yaml'
      - 'nais/nais-dev.yaml'


jobs:
  deploy:
    permissions:
      id-token: write
      contents: write

    strategy:
      matrix:
        name:
          - aiven-sykepengedager-infotrygd.yml
        cluster:
          - dev-gcp
          - prod-gcp
        include:
          - cluster: dev-gcp
            vars: nais-dev.yaml
          - cluster: prod-gcp
            vars: nais-prod.yaml
    name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.sha }}

      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v2
        env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: ${{ matrix.cluster }}
            RESOURCE: nais/${{ matrix.name }}
            VARS: nais/${{ matrix.vars }}
            PRINT_PAYLOAD: true
            VAR: image=${{ steps.build-and-push-docker-image.outputs.image }}


#
#      - name: Deploy ${{ matrix.name }} to ${{ matrix.cluster }}
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          TEAM: 'team-esyfo'
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: ${{ matrix.cluster }}
#          RESOURCE: nais/${{ matrix.name }}
#          VARS: nais/${{ matrix.vars }}
#          PRINT_PAYLOAD: true
#          VAR: image=${{ steps.docker-build-push.outputs.image }}