name: Deploy Aiven Application

on:
  push:
    paths:
      - nais/aiven-sykepengedager-infotrygd.yml
      - .github/workflows/deploy-aiven.yml
      - nais/nais-prod.yaml
      - nais/nais-dev.yaml
jobs:
  deploy-to-dev:
    name: Deploy to dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy topic sykepengedager-informasjon-aiven to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/aiven-sykepengedager-infotrygd.yml
